const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  getAllTracks: () => ipcRenderer.invoke('db:getAllTracks'),
  getPlaylists: () => ipcRenderer.invoke('db:getPlaylists'),
  getPlaylistTracks: (listId) => ipcRenderer.invoke('db:getPlaylistTracks', listId),
  searchPlaylists: (query) => ipcRenderer.invoke('db:searchPlaylists', query),
  getTrack: (trackId) => ipcRenderer.invoke('db:getTrack', trackId),
  getStats: () => ipcRenderer.invoke('db:getStats'),
  getDatabases: () => ipcRenderer.invoke('db:getDatabases'),
  switchDatabase: (dbFile) => ipcRenderer.invoke('db:switchDatabase', dbFile),
  setDbPath: (path) => ipcRenderer.invoke('db:setPath', path),
  getDbPath: () => ipcRenderer.invoke('db:getPath'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveConfig: (config) => ipcRenderer.invoke('config:save', config),
  selectFolder: () => ipcRenderer.invoke('config:selectFolder'),
  updateTrack: (trackId, fields) => ipcRenderer.invoke('db:updateTrack', trackId, fields),
  addTrackToPlaylist: (listId, trackId, databaseUuid) => ipcRenderer.invoke('db:addTrackToPlaylist', listId, trackId, databaseUuid),
  reorderPlaylistEntities: (listId, orderedEntityIds) => ipcRenderer.invoke('db:reorderPlaylistEntities', listId, orderedEntityIds),
  createPlaylist: (title, parentListId) => ipcRenderer.invoke('db:createPlaylist', title, parentListId),
  deletePlaylist: (playlistId) => ipcRenderer.invoke('db:deletePlaylist', playlistId),
  renamePlaylist: (playlistId, newTitle) => ipcRenderer.invoke('db:renamePlaylist', playlistId, newTitle),
  movePlaylist: (playlistId, newParentId) => ipcRenderer.invoke('db:movePlaylist', playlistId, newParentId),
  reorderPlaylists: (parentListId, orderedIds) => ipcRenderer.invoke('db:reorderPlaylists', parentListId, orderedIds),
  removeTrackFromPlaylist: (listId, entityId) => ipcRenderer.invoke('db:removeTrackFromPlaylist', listId, entityId),
  removeTracksFromPlaylist: (listId, entityIds) => ipcRenderer.invoke('db:removeTracksFromPlaylist', listId, entityIds),
  removeFromCollection: (trackId) => ipcRenderer.invoke('db:removeFromCollection', trackId),
  getWaveforms: (trackIds) => ipcRenderer.invoke('db:getWaveforms', trackIds),
  checkFilePaths: (data) => ipcRenderer.invoke('db:checkFilePaths', data),
  findMatchingFiles: (data) => ipcRenderer.invoke('db:findMatchingFiles', data),
  scanMusicFolders: (data) => ipcRenderer.invoke('db:scanMusicFolders', data),
  getTracksByFolder: (folderPath) => ipcRenderer.invoke('db:getTracksByFolder', folderPath),
  selectMusicFolder: () => ipcRenderer.invoke('config:selectMusicFolder'),
  loadAudio: (filePath) => ipcRenderer.invoke('audio:load', filePath)
})
